kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
# iosMain 直接使用 sherpa cinterop 符号，需把各 iOS 目标的 cinterop 共享化到 iosMain/appleMain/nativeMain
kotlin.mpp.enableCInteropCommonization=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
